remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: BerSec Chronicles
author: Rafael Gacek
description: Explore thhe uncharted realms of offensive security with BerSec Chronicles. Dive into the art and science of ethical hacking, red teaming, and cyber warfate strategies.
